trigger:
- master

resources:
- repo: self

variables:
   imageRepo: pythontest
   tag: '$(Buid.BuildId)'


stages:
- stage: Build
  displayName: Build image 
  jobs:
  - job: Build
    displayName: Build
    pool: 
      vmImage: ubuntu-latest

    steps:

    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'registry'
        repository: '$(imageRepo)'
        command: 'buildAndPush'
        Dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)
          latest

    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Pipeline.Workspace)/s'
        artifact: 'drop'
        publishlocation: 'pipeline'

# - stage: Deploy
#   displayName: Deploy to AKS
#   dependsOn: Build
#   jobs: 
#   - job: Deploy
#     displayName: deploy 
#     pool: 
#       vmImage: ubuntu-latest

#     steps:
#     - task: DownloadPipelineArtifact@2
#       inputs:
#         buildType: 'current'
#         artifact: 'drop'
#         targetPath: '$(Pipeline.Workspace)/drop'

#     - task: KubernetesManifest@0  
#       inputs:
#         action: 'deploy'
#         kubernetesServiceConnection: 'k8connection'
#         namespace: 'default'
#         manifests: $(Pipeline.Workspace)/drop/deployment.yml    
